#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${AMR_USB_ENV_FILE:-${WORKSPACE_DIR}/config/usb_ports.env}"

usage() {
    cat <<EOF
Usage:
  $0 scan
  $0 configure [--env-file PATH]
  $0 check [--env-file PATH]
  $0 print [--env-file PATH]

Devices:
  front lidar, rear lidar, motor driver, depth camera

Examples:
  $0 scan
  $0 configure
  source ${ENV_FILE}
  $0 check
EOF
}

parse_args() {
    MODE="${1:-configure}"
    if [[ $# -gt 0 ]]; then
        shift
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --env-file)
                if [[ $# -lt 2 ]]; then
                    echo "ERROR: --env-file requires a path" >&2
                    exit 2
                fi
                ENV_FILE="$2"
                shift 2
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                echo "ERROR: Unknown argument: $1" >&2
                usage
                exit 2
                ;;
        esac
    done
}

real_device() {
    local path="$1"
    readlink -f "$path" 2>/dev/null || true
}

is_char_device_path() {
    local path="$1"
    local real

    [[ -e "$path" ]] || return 1
    real="$(real_device "$path")"
    [[ -n "$real" && -c "$real" ]]
}

print_serial_candidates() {
    local path

    echo "[Serial candidates]"
    shopt -s nullglob
    for path in /dev/serial/by-id/* /dev/ttyUSB* /dev/ttyACM*; do
        if is_char_device_path "$path"; then
            printf "  %-64s -> %s\n" "$path" "$(real_device "$path")"
        fi
    done
    shopt -u nullglob
    echo
}

print_video_candidates() {
    local path

    echo "[Video candidates]"
    shopt -s nullglob
    for path in /dev/v4l/by-id/* /dev/video*; do
        if is_char_device_path "$path"; then
            printf "  %-64s -> %s\n" "$path" "$(real_device "$path")"
        fi
    done
    shopt -u nullglob
    echo
}

scan_devices() {
    echo "=============================="
    echo " AMR USB Port Scan"
    echo "=============================="
    echo
    echo "Host: $(hostname)"
    echo "Date: $(date)"
    echo

    if command -v lsusb >/dev/null 2>&1; then
        echo "[USB devices]"
        lsusb
        echo
    else
        echo "WARN: lsusb not found. Install usbutils if needed."
        echo
    fi

    print_serial_candidates
    print_video_candidates

    if command -v v4l2-ctl >/dev/null 2>&1; then
        echo "[V4L2 devices]"
        v4l2-ctl --list-devices || true
        echo
    fi
}

load_env_file() {
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
    fi
}

prompt_path() {
    local label="$1"
    local current="$2"
    local value

    while true; do
        read -r -p "${label} [${current}]: " value
        value="${value:-$current}"

        if [[ -z "$value" ]]; then
            echo "ERROR: value is required" >&2
            continue
        fi

        if is_char_device_path "$value"; then
            printf "%s" "$value"
            return 0
        fi

        echo "ERROR: '$value' is not an available character device" >&2
    done
}

write_env_file() {
    local front="$1"
    local rear="$2"
    local motor="$3"
    local depth="$4"

    mkdir -p "$(dirname "$ENV_FILE")"
    umask 022
    {
        echo "# Generated by scripts/usb_port_setup.sh"
        echo "# Source this file before running ROS launch files:"
        echo "#   source ${ENV_FILE}"
        echo
        printf "export AMR_FRONT_LIDAR_PORT=%q\n" "$front"
        printf "export AMR_REAR_LIDAR_PORT=%q\n" "$rear"
        printf "export AMR_MOTOR_DRIVER_PORT=%q\n" "$motor"
        printf "export AMR_DEPTH_CAMERA_DEVICE=%q\n" "$depth"
        echo
        printf "export FRONT_LIDAR_PORT=%q\n" "$front"
        printf "export REAR_LIDAR_PORT=%q\n" "$rear"
        printf "export MOTOR_DRIVER_PORT=%q\n" "$motor"
        printf "export DEPTH_CAMERA_DEVICE=%q\n" "$depth"
    } > "$ENV_FILE"
}

configure_devices() {
    local front
    local rear
    local motor
    local depth

    load_env_file
    scan_devices

    echo "Use /dev/serial/by-id/... for serial devices when available."
    echo "Use /dev/v4l/by-id/... for the depth camera when available."
    echo

    front="$(prompt_path "Front lidar serial port" "${AMR_FRONT_LIDAR_PORT:-}")"
    echo
    rear="$(prompt_path "Rear lidar serial port" "${AMR_REAR_LIDAR_PORT:-}")"
    echo
    motor="$(prompt_path "Motor driver serial port" "${AMR_MOTOR_DRIVER_PORT:-}")"
    echo
    depth="$(prompt_path "Depth camera video device" "${AMR_DEPTH_CAMERA_DEVICE:-}")"
    echo

    if [[ "$(real_device "$front")" == "$(real_device "$rear")" ||
          "$(real_device "$front")" == "$(real_device "$motor")" ||
          "$(real_device "$rear")" == "$(real_device "$motor")" ]]; then
        echo "ERROR: front lidar, rear lidar, and motor driver must use different serial devices" >&2
        exit 1
    fi

    write_env_file "$front" "$rear" "$motor" "$depth"

    echo "Saved: $ENV_FILE"
    echo
    print_env_summary
}

check_one() {
    local label="$1"
    local value="$2"

    if [[ -z "$value" ]]; then
        printf "FAIL: %-24s not set\n" "$label"
        return 1
    fi

    if is_char_device_path "$value"; then
        printf "OK:   %-24s %s -> %s\n" "$label" "$value" "$(real_device "$value")"
        return 0
    fi

    printf "FAIL: %-24s %s is not available\n" "$label" "$value"
    return 1
}

check_devices() {
    local failed=0

    load_env_file
    echo "Checking: $ENV_FILE"
    echo

    check_one "front lidar" "${AMR_FRONT_LIDAR_PORT:-}" || failed=1
    check_one "rear lidar" "${AMR_REAR_LIDAR_PORT:-}" || failed=1
    check_one "motor driver" "${AMR_MOTOR_DRIVER_PORT:-}" || failed=1
    check_one "depth camera" "${AMR_DEPTH_CAMERA_DEVICE:-}" || failed=1

    if [[ "$failed" -eq 0 &&
          "$(real_device "$AMR_FRONT_LIDAR_PORT")" == "$(real_device "$AMR_REAR_LIDAR_PORT")" ]]; then
        echo
        echo "FAIL: front lidar and rear lidar resolve to the same device"
        failed=1
    fi

    if [[ "$failed" -ne 0 ]]; then
        echo
        echo "USB port check failed."
        return 1
    fi

    echo
    echo "USB port check passed."
}

print_env_summary() {
    load_env_file
    echo "AMR_FRONT_LIDAR_PORT=${AMR_FRONT_LIDAR_PORT:-}"
    echo "AMR_REAR_LIDAR_PORT=${AMR_REAR_LIDAR_PORT:-}"
    echo "AMR_MOTOR_DRIVER_PORT=${AMR_MOTOR_DRIVER_PORT:-}"
    echo "AMR_DEPTH_CAMERA_DEVICE=${AMR_DEPTH_CAMERA_DEVICE:-}"
}

parse_args "$@"

case "$MODE" in
    scan)
        scan_devices
        ;;
    configure)
        configure_devices
        ;;
    check)
        check_devices
        ;;
    print)
        print_env_summary
        ;;
    *)
        echo "ERROR: Unknown mode: $MODE" >&2
        usage
        exit 2
        ;;
esac
